export const SIGN_ON_CLICKED = 'SIGN_ON_CLICKED';
export const SIGN_ON_CLOSED = 'SIGN_ON_CLOSED';
export const LOGIN_ON_CLICKED = 'LOGIN_ON_CLICKED';
export const LOGIN_ON_CLOSED = 'LOGIN_ON_CLOSED';
export const STATS_DATA = 'STATS_DATA';
export const EXCHANGE_RATE = 'EXCHANGE_RATE';
